backend:
  name: auth0
  domain: dev-ym8i3sgjqm2f84vx.us.auth0.com
  client_id: zHnAddwVTgRsae4YbTXivIp77nJn5hN0
  auth_path: "/admin/callback"


media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "albums"
    label: "Albums"
    folder: "gallery-data"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Album Title" }
      - { name: "category", label: "Category", widget: "select", options: ["studio", "family", "portrait", "events"] }
      - { name: "photos", label: "Photos", widget: "list", fields: [
          { name: "image", label: "Image", widget: "image" },
          { name: "caption", label: "Caption", widget: "string", required: false }
        ]}
